### PR TITLE
Fogging

### PR DESCRIPTION
**Pull request by CuteMoonGod**
Removed commented out code
Fixed values to intended defaults
Fixed fog built up calc so that the AC coef also reduces fog build up due to fatigue

### CODE REVIEW

**Comment by CuteMoonGod** [comment]
Wrong *repo, my bad

**Comment by diwako** [comment]
Hey as long as it becomes a pr in the future i guess ¯\_(ツ)_/¯

**Comment by CuteMoonGod** [comment]
Alright then 😄 
Reopening. Feel free to tell me if there's thing that need changing =)

**Comment by diwako** [comment]
probably best to make a new pr with the changes from your master. I however straight away say the fogging feature is a neat idea, i totally forgot that was a thing. guess i blanked it out of my mind when i had respirator gear training, i hated that a lot.

The geiger counter is also a neat idea, tho i would prefer to have the beep option still. For code improvements ( i already spied a little, ngl) i have some suggestions but that would be for the new pr.

**Comment by CuteMoonGod** [comment]
Will do.

**Pull request closed without merging**
